-- Index sur gcd_issues(series_id) — « séries en cours & tome suivant » (#30, lot B).
--
-- La table portait déjà ses index d'IDENTIFICATION (barcode, préfixe, isbn,
-- gcd_id) : tous partent d'un code pour retrouver UNE issue. Le tome suivant
-- pose la question inverse — « tous les numéros connus de CETTE série » — et
-- attaquait donc 559 516 lignes en seq scan à chaque affichage des stats.
--
-- L'index couvre en plus `number` : la requête du catalogue ne lit que ces deux
-- colonnes, elle se sert donc entièrement dans l'index (index-only scan), sans
-- jamais toucher la table.
-- `if not exists` : l'index a été créé directement en base avant d'être
-- enregistré dans l'historique des migrations (cf. réconciliation par
-- `supabase migration repair`, PR #99). Le garde rend le rejeu inoffensif,
-- ici comme sur un environnement reconstruit de zéro.
create index if not exists gcd_issues_series_id_idx on gcd_issues (series_id, number);
